---
# how execute:  ansible-playbook main.yml  --vault-id ~/vault-password-file
- hosts: localhost
  connection: local
  gather_facts: true
  vars_files: 
    - aws.credentials
    
  tasks:
    - name: check if instance already created
      ec2_instance_facts:
        filters:
          "tag:Name": udemy-fe
          "instance-state-name": running 
      register: ec2_instance
    # - debug:
    #     var: ec2_instance.instances
    - name: Create instances if not alreeady created and running
      block:
      - name: Create ec2-fe instances 
        ec2:
          key_name: alex_test_aws
          group: permit-ssh
          instance_type: t2.micro
          image: ami-09def150731bdbcc2
          region: eu-central-1
          wait: yes
          exact_count: 2
          count_tag:
              Name: Udemy
          instance_tags:
              Name: udemy-fe
        register: ec2
     
      - name: Wait for SSH to come up
        local_action: wait_for 
                host={{ item.public_ip }} 
                port=22 
                state=started
        with_items: "{{ ec2.instances }}"
      - debug:
          msg: "###### instance created ######"
      when:
        ec2_instance.instances == [ ]
 
    - debug:
       var:  ec2_instance.instances |length

    - debug:
       var:  public_ip
      with_dict: "{{ ec2_instance.instances }}"